# Generated by Django 3.1.3 on 2020-11-26 02:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20201125_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 21, 49, 1, 46239), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.type'),
        ),
    ]
