# Generated by Django 3.1.3 on 2020-11-26 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201125_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombres')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 21, 51, 31, 925769), verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cat',
            field=models.ManyToManyField(to='erp.Category'),
        ),
    ]
